In [138]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [11]:
df = pd.read_csv('energydata_complete (1).csv')

In [18]:
df

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [7]:
# column_names = {'T1': 'Temperature_in_kitchen area', 'RH_1': 'Humidity_in_kitchen_area', 
#                'T2': 'Temperature_in_living_room_area', 'RH_2': 'Humidity_in_livingroom_area',
#                'T3': 'Temperature_in_laundry_room_area', 'RH_3': 'Humidity_in_laundry_room_area',
#                'T4': 'Temperature_in_office_room', 'RH_4': 'Humidity_in_office_room',
#                'T5': 'Temperature_in_bathroom', 'RH_5': 'Humidity_in_bathroom',
#                'T6': 'Temperature_outside_the_building', 'RH_6': 'Humidity_outside_the_building',
#                'T7': 'Temperature_in_ironing_room', 'RH_7': 'Humidity_in_ironing_room',
#                'T8': 'Temperature_in_teenager_room 2', ''}

In [8]:
# Normalise the dataset

In [ ]:
# Normalize the dataset using the MinMaxScaler after removing the following columns: [“date”, “lights”].
# The target variable is “Appliances”. Use a 70-30 train-test set split with a random state of 42
# (for reproducibility). Run a multiple linear regression using the training set and evaluate your
# model on the test set. Answer the following questions:

# What is the Mean Absolute Error (in two decimal places)?

In [9]:
scaler = MinMaxScaler()

In [14]:
df = df.drop(columns=['date', 'lights'])

In [23]:
normalised_data = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [24]:
normalised_data

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.084112,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,...,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.074766,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,...,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.242991,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,...,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.383178,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,...,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.392523,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,...,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [81]:
features_df = normalised_data.drop(columns = ['Appliances'], axis=1)

In [82]:
target_var = normalised_data['Appliances']

In [83]:
# split data into training and testing

In [126]:
x_train, x_test, y_train, y_test = train_test_split(features_df, target_var, test_size=0.3, random_state = 42)

In [127]:
linear_model= LinearRegression()

In [128]:
y = linear_model.fit(x_train, y_train)

In [129]:
predicted_value = linear_model.predict(x_test)

In [130]:
predicted_value

array([0.03322944, 0.24416608, 0.03421016, ..., 0.06833667, 0.10029592,
       0.05737411])

# FIND THE MEAN ABSOLUTE ERROR

In [116]:
mae = mean_absolute_error(y_test, predicted_value)

In [117]:
round(mae, 2)

0.05

## What is the Root Mean Squared Error (in three decimal places)?

In [118]:
rmse= np.sqrt(mean_squared_error(y_test, predicted_value))

In [119]:
round(rmse, 3)

0.088

## What is the Residual Sum of Squares (in two decimal places)?

In [120]:
rss = np.sum(np.sqrt(y_test - predicted_value))

C:\Users\ayool\anaconda3\envs\data\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [131]:
round(rss, 2)

392.65

## What is the Coefficient of Determination (in two decimal places)?

In [132]:
r2 = r2_score(y_test, predicted_value)

In [133]:
round(r2, 2)

0.15

## Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [136]:
ridge_weight = Ridge(alpha=0.5)

In [137]:
ridge_weight.fit(x_train, y_train)

Ridge(alpha=0.5)

In [139]:
lasso_weight = Lasso(alpha = 0.01)

In [140]:
lasso_weight.fit(x_train, y_train)

Lasso(alpha=0.01)

In [143]:
def get_weight(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights ).reset_index()
    weights_df.columns = ['features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [145]:
linear_model_weights = get_weight(linear_model, x_train, 'Linear_Mode_weights')
ridge_reg_weights = get_weight(ridge_weight, x_train, 'Ridge_reg_Weights')
lasso_reg_weights = get_weight(lasso_weight, x_train, 'Lasso_reg_weights')

In [148]:
final_weights = pd.merge(linear_model_weights, ridge_reg_weights, on='features')
final_weights = pd.merge(final_weights, lasso_reg_weights, on='features')

In [149]:
final_weights

       features  Linear_Mode_weights  Ridge_reg_Weights  Lasso_reg_weights
0           rv2        -2.219382e+11           0.000743               -0.0
1          RH_2        -4.567672e-01          -0.401134               -0.0
2         T_out        -3.219552e-01          -0.250765                0.0
3            T2        -2.361994e-01          -0.193880                0.0
4            T9        -1.899314e-01          -0.188584                0.0
5          RH_8        -1.576020e-01          -0.156596               -0.0
6        RH_out        -7.768452e-02          -0.050541               -0.0
7          RH_7        -4.455266e-02          -0.046291               -0.0
8          RH_9        -3.980932e-02          -0.041701               -0.0
9            T5        -1.566960e-02          -0.020727                0.0
10           T1        -3.281051e-03          -0.021549                0.0
11  Press_mm_hg         6.853755e-03           0.006516               -0.0
12           T7         1.027363e-02           0.010021                0.0
13   Visibility         1.228672e-02           0.012032                0.0
14         RH_5         1.601549e-02           0.016176                0.0
15         RH_4         2.634730e-02           0.024168                0.0
16           T4         2.896918e-02           0.027006                0.0
17    Windspeed         2.919433e-02           0.030463                0.0
18         RH_6         3.808434e-02           0.035023               -0.0
19         RH_3         9.595330e-02           0.094976                0.0
20           T8         1.020164e-01           0.100754                0.0
21    Tdewpoint         1.178010e-01           0.076668                0.0
22           T6         2.364816e-01           0.213316                0.0
23           T3         2.907042e-01           0.287408                0.0
24         RH_1         5.536721e-01           0.511932                0.0
25          rv1         2.219382e+11           0.000743               -0.0

## Train a ridge regression model with an alpha value of 0.4. 
## Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [150]:
ridge_reg= Ridge(alpha=0.4)

In [162]:
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.4)

In [173]:
predicted_value = ridge_reg .predict(x_test)

In [174]:
RMSE = np.sqrt(mean_squared_error (y_test, predicted_value ))

In [184]:
print(f'The Root Mean Squared Error using Ridge regression is : {round(RMSE, 3)}, so no, there\'s no difference')

The Root Mean Squared Error using Ridge regression is : 0.088, so no, there's no difference

In [177]:
lasso_regr = Lasso(alpha = 0.001)

In [178]:
lasso_regr.fit(x_train, y_train)

Lasso(alpha=0.001)

In [179]:
predicted_value = lasso_regr.predict(x_test)

In [180]:
R_mse = np.sqrt(mean_squared_error(y_test, predicted_value ))

In [182]:
print(f'The Root Mean Squared Error using Lasso regression is : {round(R_mse, 3)}')

The Root Mean Squared Error using Lasso regression is : 0.094

In [159]:
lasso_reg = get_weight(lasso_regr, x_train, 'Lasso_reg_weights')

In [160]:
lasso_reg

       features  Lasso_reg_weights
0        RH_out          -0.049557
1          RH_8          -0.000110
2            T1           0.000000
3     Tdewpoint           0.000000
4    Visibility           0.000000
5   Press_mm_hg          -0.000000
6         T_out           0.000000
7          RH_9          -0.000000
8            T9          -0.000000
9            T8           0.000000
10         RH_7          -0.000000
11          rv1          -0.000000
12           T7          -0.000000
13           T6           0.000000
14         RH_5           0.000000
15           T5          -0.000000
16         RH_4           0.000000
17           T4          -0.000000
18         RH_3           0.000000
19           T3           0.000000
20         RH_2          -0.000000
21           T2           0.000000
22         RH_6          -0.000000
23          rv2          -0.000000
24    Windspeed           0.002912
25         RH_1           0.017880

In [161]:
print('There are 4  features that have non-zero feature weights')

There are 4  features that have non-zero feature weights